ckpt_path_flairhub_rgb_large = "ckpt/FLAIR-HUB_LC-A_RGB_swinlarge-upernet.safetensors"
ckpt_path_flairhub_rgb_base = "ckpt/FLAIR-HUB_LC-A_RGB_swinbase-upernet.safetensors"
ckpt_path_flairhub_rgb_small = "ckpt/FLAIR-HUB_LC-A_RGB_swinsmall-upernet.safetensors"
ckpt_path_flairhub_rgb_tiny = "ckpt/FLAIR-HUB_LC-A_RGB_swintiny-upernet.safetensors"
ckpt_path_flairhub_ir = "ckpt/FLAIR-HUB_LC-A_IR_swinbase-upernet.safetensors"
ckpt_path_flairinc_rgb = "ckpt/FLAIR-INC_rgb_15cl_resnet34-unet_weights.pth"
ckpt_path_flairinc_rgbi = "ckpt/FLAIR-INC_rgbi_15cl_resnet34-unet_weights.pth"
