exp_name: "flairhub_small_linear_rgb_only"
env:
  device: "cuda"  # "cuda" or "cpu"
  num_workers: 8
data:
  root_path: "dataset_jpg"
  dataset_ext: "jpg"  # "tif", "jpg", "jpeg", or "png"
  batch_size: 4
  collate_fn: "fixed"  # "fixed" or "max"
  n_classes: 10
  n_years: 26
  channel_dropout: true
  data_augmentation: true
model:
  backbone: "flairhub"  # "flairhub" or "flairinc"
  size: "small"  # "tiny", "small", "base", or "large"
  rgb_only: true
  use_float16: true
  fuse_mode: "average"  # "average" or "concat"
  classifier : 'linear'  # "ltae" or 'linear'
  ltae_mode : "att"  # "att" ou "mlp"
  k_kernel : 3
training:
  num_epochs: 50
  learning_rate: 0.0001
  weight_decay: 0.001
  print_interval: 500
  resume: false  # Whether to resume training from the last checkpoint in the results folder.
  soft_sigma : 0.5 # 0 = one-hot
