exp_name: "flair_hub_seuils_rgb_only_5_small"
env:
  device: "cuda"  # "cuda" or "cpu"
  num_workers: 8
data:
  root_path: "dataset_jpg"
  dataset_ext: "jpg"  # "tif", "jpg", "jpeg", or "png"
  batch_size: 4
  collate_fn: "fixed"  # "fixed" or "max"
  n_classes: 10
  n_years: 26
  building_class_idx: 1
model:
  backbone: "flairhub"  # "flairhub" or "flairinc"
  size: "small"  # "tiny", "small", "base", or "large"
  rgb_only: true
  use_float16: true
method:
  seuils: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95]
  print_interval: 500
  detection_mode: "first"